apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    discovery.kubernetes "pods" {
      role = "pod"
    }

    loki.write "default" {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      }
    }

    loki.source.kubernetes "logs" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.write.default.receiver]
    }

    prometheus.remote_write "default" {
      endpoint {
        url = "http://prometheus-server.monitoring.svc.cluster.local/api/v1/write"
      }
    }

    prometheus.scrape "self" {
      targets = [{ __address__ = "127.0.0.1:12345" }]
      forward_to = [prometheus.remote_write.default.receiver]
    }