apiVersion: apps/v1
kind: Deployment
metadata:
  name: onthetop-cnn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onthetop-cnn
  template:
    metadata:
      labels:
        app: onthetop-cnn
    spec:
      containers:
        - name: cnn
          image: luckyprice1103/onthetop-cnn:latest
          ports:
            - containerPort: 8000
          # env:
          #   - name: CNN_MODEL
          #     value: /app/models/desk_classify.h5
---
apiVersion: v1
kind: Service
metadata:
  name: onthetop-cnn
spec:
  selector:
    app: onthetop-cnn
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
