# helmfile-ingress.yaml

releases:
  - name: aws-cloud-controller-manager
    namespace: kube-system
    chart: aws-cloud-controller-manager/aws-cloud-controller-manager
    version: 1.27.1
    values:
      - cloudProvider: aws
        region: ap-northeast-2
        clusterName: onthetop-cluster
        serviceAccount:
          create: true
          name: cloud-controller-manager

  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.12.3
    values:
      - controller:
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
          replicaCount: 1
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          admissionWebhooks:
            enabled: false
