# dev/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onthetop-backend-secrets-dev # ★ 1. 이름 변경: dev 접미사 추가
  namespace: onthetop-backend-dev   # ★ 2. 네임스페이스 변경: dev용으로 지정
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager-cluster-store # ★ ClusterSecretStore는 모든 네임스페이스에서 공유하므로 그대로 사용
    kind: ClusterSecretStore
  target:
    name: onthetop-backend-secrets-dev # ★ 3. 생성될 쿠버네티스 Secret 이름 변경
    creationPolicy: Owner
    template:
      data:
        secrets.properties: "{{ .secrets_properties_file_content }}"
  data:
    - secretKey: secrets_properties_file_content
      remoteRef:
        key: onthetop/backend/dev/secrets-properties # ★ 4. AWS Secret 이름 변경: 1단계에서 만든 개발용 Secret 이름으로 지정
