- hosts: all
  become: true
  roles:
    - common

- hosts: monitoring
  become: true
  roles:
    - certbot
    - nginx
    - prometheus
    - grafana
    - alertmanager
    - loki

- hosts: blackbox
  become: true
  roles:
    - blackbox_exporter

- hosts: monitoring_targets_shared
  become: true
  roles:
    - node_exporter
    - { role: mysql_exporter, when: "'mysql_servers' in group_names" }

- hosts: monitoring_targets_dev
  become: true
  roles:
    - node_exporter
    - { role: mysql_exporter, when: "'mysql_servers' in group_names" }
    - { role: promtail, when: "'promtail_targets' in group_names" }

- hosts: monitoring_targets_prod
  become: true
  roles:
    - node_exporter
    - { role: mysql_exporter, when: "'mysql_servers' in group_names" }
    - { role: promtail, when: "'promtail_targets' in group_names" }

- hosts: monitoring_targets_gpu
  become: true
  roles:
    - node_exporter
    - { role: promtail, when: "'promtail_targets' in group_names" }
