# application-gitops-repo/kubernetes/onthetop-backend/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onthetop-backend-secrets # ESO가 EKS 클러스터에 생성할 Kubernetes Secret의 이름
  namespace: onthetop-backend # 이 ExternalSecret과 생성될 Kubernetes Secret이 위치할 네임스페이스
spec:
  refreshInterval: "1h" # ESO가 AWS Secrets Manager에서 시크릿 값을 동기화할 주기 (예: 1시간마다)
  secretStoreRef:
    name: aws-secrets-manager-cluster-store # 이전에 Terraform으로 생성한 ClusterSecretStore의 이름
    kind: ClusterSecretStore # SecretStore가 아닌 ClusterSecretStore를 참조합니다.
  target:
    name: onthetop-backend-secrets # Kubernetes Secret의 이름 (metadata.name과 동일하게 설정)
    creationPolicy: Owner # ExternalSecret 리소스가 삭제될 때, 생성된 Kubernetes Secret도 함께 삭제됩니다.
    template:
      # AWS Secrets Manager에서 가져온 전체 시크릿 값을 'secrets.properties'라는 키로 Kubernetes Secret에 저장합니다.
      # 이렇게 저장된 키는 나중에 Pod 볼륨 마운트 시 파일 이름이 됩니다.
      data:
        secrets.properties: "{{ .secrets_properties_file_content }}" # .secrets_properties_file_content는 아래 data[0].secretKey와 연결됩니다.
  data:
    # AWS Secrets Manager에서 가져올 시크릿의 세부 정보
    - secretKey: secrets_properties_file_content # Kubernetes Secret의 임시 키 이름 (template에서 참조)
      remoteRef:
        key: onthetop/backend/secrets-properties # AWS Secrets Manager에 저장된 시크릿의 실제 이름
        # property: (AWS Secrets Manager 시크릿이 JSON이 아닌 단순 텍스트라면 property 필드는 필요 없습니다.)
        #           만약 secrets.properties 파일 내용이 JSON이 아니라 순수 텍스트라면 이 'property' 라인은 제거해야 합니다.
