name: Rollback Docker Prod (Safe)

on:
  workflow_dispatch:
    inputs:
      be_version:
        description: '현재 잘못 배포된 docker 배포 버전 (예: 1.2.3)'
        required: true
      fe_slot:
        description: '현재 잘못 배포된 FE 슬롯 (예: blue, green)'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    env:
      REGION: asia-northeast3
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      AWS_DEFAULT_REGION: ap-northeast-2

    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CLOUDFRONT_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CLOUDFRONT_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Set variables
        id: vars
        run: |
          REGION="${{ env.REGION }}"
      
          MIG_NAME="onthetop-mig-prod"
      
          echo "region=$REGION" >> $GITHUB_OUTPUT
          echo "mig_name=$MIG_NAME" >> $GITHUB_OUTPUT


      - name: Get list of backend instance IPs
        id: get_ips
        run: |

          MIG="${{ steps.vars.outputs.mig_name }}"
          REGION="${{ steps.vars.outputs.region }}"
          INSTANCE_NAMES=$(gcloud compute instance-groups managed list-instances "$MIG" \
            --region="$REGION" \
            --format="get(instance)" | sed -n 's|.*/||p')
          
          if [ -z "$INSTANCE_NAMES" ]; then
            echo "❌ MIG 인스턴스를 찾을 수 없습니다. MIG 이름과 REGION을 확인하세요."
            exit 1
          fi


          ZONE_CANDIDATES=("asia-northeast3-a" "asia-northeast3-b" "asia-northeast3-c")

          IP_LIST=""
          for INSTANCE in $INSTANCE_NAMES; do
            for TRY_ZONE in "${ZONE_CANDIDATES[@]}"; do
              IP=$(gcloud compute instances describe "$INSTANCE" --zone "$TRY_ZONE" \
                --format="get(networkInterfaces[0].networkIP)" 2>/dev/null) || continue
              if [ -n "$IP" ]; then
                echo "✅ $INSTANCE ($TRY_ZONE) → $IP"
                IP_LIST+="$IP,"
                break
              fi
            done
          done

          IP_LIST="${IP_LIST%,}"

          echo " All IPs: $IP_LIST"
          echo "slot_ips=$IP_LIST" >> $GITHUB_OUTPUT

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.JUMP_SSH_KEY }}" > ~/.ssh/jump_key
          chmod 600 ~/.ssh/jump_key

          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/dev_key
          chmod 600 ~/.ssh/dev_key

      - name: Rollback Backend with MIG Health Check
        env:
          SLOT_IPS: ${{ steps.get_ips.outputs.slot_ips }}
          RAW_CANCEL_VERSION: ${{ github.event.inputs.be_version }}
          JUMP_HOST: ${{ secrets.JUMP_SSH_HOST }}
        run: |
          CANCEL_VERSION="v$RAW_CANCEL_VERSION"
          mkdir -p ~/.ssh
          ssh-keyscan -H "$JUMP_HOST" >> ~/.ssh/known_hosts
          echo "📦 SLOT_IPS 값: $SLOT_IPS"
          IFS=',' read -ra IPS <<< "$SLOT_IPS"
          echo "🔍 분해된 IP 배열: ${IPS[@]}"
          echo "🔍 배열 길이: ${#IPS[@]}"

          for IP in "${IPS[@]}"; do
            # ssh-keyscan -H "$IP" >> ~/.ssh/known_hosts || echo "⚠️ ssh-keyscan 실패: $IP"
            echo "🚀 Deploying to $IP..."
            ssh -o StrictHostKeyChecking=no \
                -o UserKnownHostsFile=/dev/null \
                -o ProxyCommand="ssh -i ~/.ssh/jump_key -W %h:%p ubuntu@$JUMP_HOST" -i ~/.ssh/dev_key ubuntu@$IP \

                CANCEL_VERSION=$CANCEL_VERSION bash -s <<'EOF'
                set -ex


                SLOTS_RUNNING=$(sudo docker ps --format '{{.Names}}' | grep '^onthetop-backend-' | wc -l)
                INSTANCE_NAME=$(hostname)

                if [ "$SLOTS_RUNNING" -ne 2 ]; then
                echo "❌ Error: '$INSTANCE_NAME' 인스턴스에서 실행 중인 도커가 정확히 2개가 아닙니다. (현재: $SLOTS_RUNNING개)"
                sudo docker ps --format '  → {{.Names}}  ({{.Status}})' | grep '^  → onthetop-backend-'
                exit 1
                fi


                BLUE_CONTAINER="onthetop-backend-blue"
                GREEN_CONTAINER="onthetop-backend-green"

                BLUE_VERSION=$(sudo docker inspect --format='{{index .Config.Image}}' "$BLUE_CONTAINER" 2>/dev/null | cut -d: -f2 || echo "")
                GREEN_VERSION=$(sudo docker inspect --format='{{index .Config.Image}}' "$GREEN_CONTAINER" 2>/dev/null | cut -d: -f2 || echo "")

                ACTIVE_PORT=$(grep "proxy_pass" /etc/nginx/sites-enabled/backend | grep -oE '[0-9]+')
                if [ "$ACTIVE_PORT" = "8080" ]; then
                    ACTIVE_SLOT=blue
                    OLD_SLOT=green
                    OLD_PORT=8081
                else
                    ACTIVE_SLOT=green
                    OLD_SLOT=blue
                    OLD_PORT=8080
                fi

                # 🔐 현재 Nginx가 바라보는 슬롯의 버전이 CANCEL_VERSION과 일치하는지 확인
                ACTIVE_VERSION=$(sudo docker inspect --format='{{index .Config.Image}}' onthetop-backend-$ACTIVE_SLOT 2>/dev/null | cut -d: -f2 || echo "")
                if [ "$ACTIVE_VERSION" != "$CANCEL_VERSION" ]; then
                  echo "❌ 현재 Nginx가 바라보는 슬롯($ACTIVE_SLOT)의 버전은 $ACTIVE_VERSION 입니다."
                  echo "⚠️ 입력한 CANCEL_VERSION ($CANCEL_VERSION)과 일치하지 않습니다. 롤백 중단."
                  exit 1
                fi


                OLD_VERSION=$(sudo docker inspect --format='{{index .Config.Image}}' onthetop-backend-$OLD_SLOT 2>/dev/null | cut -d: -f2 || echo "")
                if [ "$OLD_VERSION" = "$CANCEL_VERSION" ]; then
                  echo "❌ 롤백 대상 슬롯이 문제 버전($CANCEL_VERSION)과 동일합니다. 롤백 불가."
                  exit 1
                fi

                echo " 현재 슬롯: $ACTIVE_SLOT → 롤백 슬롯: $OLD_SLOT (포트: $OLD_PORT)"

                # ✅ Health check
                STATUS="000"
                for i in {1..10}; do
                  echo " [$i/10] Checking health on port $OLD_PORT..."
                  STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:$OLD_PORT/api/v1/health || echo "000")
                  if [ "$STATUS" = "200" ]; then
                    echo "✅ Health check passed!"
                    break
                  fi
                  sleep 10
                done

                if [ "$STATUS" != "200" ]; then
                  echo "❌ Health check failed after 10 attempts."
                  exit 1
                fi

                # 🔁 Nginx 설정 변경
                echo "🔁 Switching Nginx to $OLD_SLOT (port $OLD_PORT)..."
                NGINX_CONF="/etc/nginx/sites-enabled/backend"

                echo "server {
                  listen 80;
                  server_name _;
                  location / {
                    proxy_pass http://localhost:$OLD_PORT;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  }
                }" | sudo tee "$NGINX_CONF" > /dev/null

                echo "✅ Nginx config updated to route to port $OLD_PORT"
                echo "🔄 Reloading Nginx..."
                sudo nginx -t
                sudo systemctl reload nginx

                ROLLBACK_LOG="/var/log/rollback.log"
                TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')


                echo "[$TIMESTAMP] [$INSTANCE_NAME] 롤백 결과" | sudo tee -a $ROLLBACK_LOG > /dev/null
                echo "  🔵 BLUE 버전  : $BLUE_VERSION" | sudo tee -a $ROLLBACK_LOG > /dev/null
                echo "  🟢 GREEN 버전 : $GREEN_VERSION" | sudo tee -a $ROLLBACK_LOG > /dev/null
                echo "  🎯 ACTIVE SLOT: $ACTIVE_SLOT (버전: $ACTIVE_VERSION)" | sudo tee -a $ROLLBACK_LOG > /dev/null
                echo "  🔁 ROLLBACK →  $OLD_SLOT (버전: $OLD_VERSION, 포트: $OLD_PORT)" | sudo tee -a $ROLLBACK_LOG > /dev/null
                echo "  ✅ Health Check: 통과" | sudo tee -a $ROLLBACK_LOG > /dev/null
                echo "" | sudo tee -a $ROLLBACK_LOG > /dev/null
          EOF
          done

      - name: Rollback CloudFront FE Origin
        run: |
          SLOT="${{ github.event.inputs.fe_slot }}"
          if [[ "$SLOT" == "blue" ]]; then
            TARGET="green"
          else
            TARGET="blue"
          fi

          echo "🔄 FE 슬롯을 $TARGET 으로 되돌립니다."
          aws cloudfront get-distribution-config --id "$CLOUDFRONT_DISTRIBUTION_ID" > raw.json

          ETAG=$(jq -r '.ETag' raw.json)
          jq '.DistributionConfig' raw.json > config-only.json

          jq --arg TARGET "$TARGET" \
            '.Origins.Items[0].OriginPath = "/frontend/prod/\($TARGET)"' \
            config-only.json > updated-config.json

          aws cloudfront update-distribution \
            --id "$CLOUDFRONT_DISTRIBUTION_ID" \
            --if-match "$ETAG" \
            --distribution-config file://updated-config.json

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
            --paths "/" "/index.html" "/assets/*.js" "/assets/*.css"
