name: Deploy Docker Prod For Several Mig

on:
  workflow_dispatch:
    inputs:
      be_version:
        description: '배포할 BE docker 버전 (예: 1.2.3)'
        required: true
      fe_version:
        description: '배포할 FE 버전 (예: 1.2.3)'
        required: true
      fe_slot:
        description: 'FE 슬롯 선택 (예: blue, green)'
        required: true
        default: 'green'
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      fe_slot: ${{ steps.vars.outputs.fe_slot }}

    env:
      AWS_DEFAULT_REGION: ap-northeast-2
      REGION: asia-northeast3
      GH_FE_REPO: 100-hours-a-week/16-Hot6-fe

    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set variables
        id: vars
        run: |
          RAW_BE_VERSION="${{ github.event.inputs.be_version }}"
          BE_VERSION="v$RAW_BE_VERSION"
          FE_VERSION="${{ github.event.inputs.fe_version }}"
          FE_SLOT="${{ github.event.inputs.fe_slot }}"
          REGION="${{ env.REGION }}"
      
          MIG_NAME="onthetop-mig-prod"
      
          echo "be_version=$BE_VERSION" >> $GITHUB_OUTPUT
          echo "fe_version=$FE_VERSION" >> $GITHUB_OUTPUT
          echo "fe_slot=$FE_SLOT" >> $GITHUB_OUTPUT
          echo "region=$REGION" >> $GITHUB_OUTPUT
          echo "mig_name=$MIG_NAME" >> $GITHUB_OUTPUT

      # ------------------ FE 업로드 ------------------

      - name: Download FE artifact from GitHub Release
        run: |
          curl -L -o fe.zip https://github.com/$GH_FE_REPO/releases/download/v${{ steps.vars.outputs.fe_version }}/frontend-prod-build.zip
          unzip -o fe.zip -d fe-dist

      - name: Upload FE to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws s3 sync fe-dist/ s3://onthe-top/frontend/prod/${{ steps.vars.outputs.fe_slot }} --delete

      # ------------------ BE 배포 ------------------

      - name: Find all instance IPs from MIG
        id: get_ips
        run: |
          MIG="${{ steps.vars.outputs.mig_name }}"
          REGION="${{ steps.vars.outputs.region }}"

          echo " Getting instance from MIG: $MIG in $REGION"

          INSTANCE_NAMES=$(gcloud compute instance-groups managed list-instances "$MIG" \
            --region="$REGION" \
            --format="get(instance)" | sed -n 's|.*/||p')

          if [ -z "$INSTANCE_NAMES" ]; then
            echo "❌ MIG 인스턴스를 찾을 수 없습니다. MIG 이름과 REGION을 확인하세요."
            exit 1
          fi

          ZONE_CANDIDATES=("asia-northeast3-a" "asia-northeast3-b" "asia-northeast3-c")

          IP_LIST=""
          for INSTANCE in $INSTANCE_NAMES; do
            for TRY_ZONE in "${ZONE_CANDIDATES[@]}"; do
              IP=$(gcloud compute instances describe "$INSTANCE" --zone "$TRY_ZONE" \
                --format="get(networkInterfaces[0].networkIP)" 2>/dev/null) || continue
              if [ -n "$IP" ]; then
                echo "✅ $INSTANCE ($TRY_ZONE) → $IP"
                IP_LIST+="$IP,"
                break
              fi
            done
          done

          IP_LIST="${IP_LIST%,}"

          echo "📦 All IPs: $IP_LIST"
          echo "slot_ips=$IP_LIST" >> $GITHUB_OUTPUT

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.JUMP_SSH_KEY }}" > ~/.ssh/jump_key
          chmod 600 ~/.ssh/jump_key

          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/dev_key
          chmod 600 ~/.ssh/dev_key

      - name: Deploy to All MIG Instances via Jump Host
        env:
          SLOT_IPS: ${{ steps.get_ips.outputs.slot_ips }}
          BE_VERSION: ${{ steps.vars.outputs.be_version }}
          JUMP_HOST: ${{ secrets.JUMP_SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$JUMP_HOST" >> ~/.ssh/known_hosts
          echo "📦 SLOT_IPS 값: $SLOT_IPS"
          IFS=',' read -ra IPS <<< "$SLOT_IPS"
          echo "🔍 분해된 IP 배열: ${IPS[@]}"
          echo "🔍 배열 길이: ${#IPS[@]}"

          for IP in "${IPS[@]}"; do
            # ssh-keyscan -H "$IP" >> ~/.ssh/known_hosts || echo "⚠️ ssh-keyscan 실패: $IP"
            echo "🚀 Deploying to $IP..."
            ssh -o StrictHostKeyChecking=no \
                -o UserKnownHostsFile=/dev/null \
                -o ProxyCommand="ssh -i ~/.ssh/jump_key -W %h:%p ubuntu@$JUMP_HOST" -i ~/.ssh/dev_key ubuntu@$IP \
                BE_VERSION=$BE_VERSION bash -s <<'EOF'
                set -ex


                SLOTS_RUNNING=$(sudo docker ps --format '{{.Names}}' | grep '^onthetop-backend-' | wc -l)
                INSTANCE_NAME=$(hostname) 
                if [ "$SLOTS_RUNNING" -gt 1 ]; then
                  echo "❌ Error: '$INSTANCE_NAME' 인스턴스에서 이미 실행중인 도커가 2개입니다."
                  sudo docker ps --format '  → {{.Names}}  ({{.Status}})' | grep '^  → onthetop-backend-'
                  exit 1
                fi

                # 🔍 현재 실행 중인 슬롯 확인
                CURRENT_SLOT=$(sudo docker ps --format '{{.Names}}' | grep onthetop-backend- | sed 's/onthetop-backend-//')
                echo "현재 실행 중인 컨테이너: $CURRENT_SLOT"
                if [ -z "$CURRENT_SLOT" ]; then
                  echo " 실행 중인 컨테이너가 없습니다. 기본값으로 blue 선택"
                  CURRENT_SLOT="none"
                  NEW_SLOT="blue"
                  PORT=8080
                elif [ "$CURRENT_SLOT" = "blue" ]; then
                  NEW_SLOT="green"
                  PORT=8081
                else
                  NEW_SLOT="blue"
                  PORT=8080
                fi

                echo " 현재 슬롯: $CURRENT_SLOT → 새 슬롯: $NEW_SLOT (포트: $PORT)"

                # 🐳 Docker 이미지 Pull & 실행
                sudo docker rm -f "onthetop-backend-$NEW_SLOT" || true
                sudo docker pull luckyprice1103/onthetop-backend:$BE_VERSION
                sudo docker run -d \
                  --name "onthetop-backend-$NEW_SLOT" \
                  -p "$PORT":8080 \
                  --memory=512m \
                  --cpus=0.5 \
                  -v /home/ubuntu/backend/secrets.properties:/app/secrets.properties \
                  -v /var/log/onthetop/backend:/logs \
                  -e SPRING_PROFILES_ACTIVE=prod \
                  luckyprice1103/onthetop-backend:$BE_VERSION \
                  --logging.file.name=/logs/backend.log \
                  --spring.config.additional-location=file:/app/secrets.properties

                # ✅ Health check
                STATUS="000"
                for i in {1..10}; do
                  echo " [$i/10] Checking health on port $PORT..."
                  STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:$PORT/api/v1/health || echo "000")
                  if [ "$STATUS" = "200" ]; then
                    echo "✅ Health check passed!"
                    break
                  fi
                  sleep 10
                done

                if [ "$STATUS" != "200" ]; then
                  echo "❌ Health check failed after 10 attempts."
                  exit 1
                fi

                # 🔁 Nginx 설정 변경
                echo "🔁 Switching Nginx to $NEW_SLOT (port $PORT)..."
                NGINX_CONF="/etc/nginx/sites-enabled/backend"

                echo "server {
                  listen 80;
                  server_name _;
                  location / {
                    proxy_pass http://localhost:$PORT;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  }
                }" | sudo tee "$NGINX_CONF" > /dev/null

                echo "✅ Nginx config updated to route to port $PORT"
                echo "🔄 Reloading Nginx..."
                sudo nginx -t
                sudo systemctl reload nginx
          EOF
          done


      # ------------------ CloudFront Origin 변경 및 무효화 ------------------

  cdn-update:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFRONT_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFRONT_SECRET_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-2
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
    steps:
      - name: Update CloudFront Origin
        run: |
          SLOT="${{ needs.deploy.outputs.fe_slot }}"
          DIST_ID="$CLOUDFRONT_DISTRIBUTION_ID"

          # 원본 전체 구성 받아오기
          aws cloudfront get-distribution-config --id $DIST_ID > raw.json

          # ETag 추출
          ETAG=$(jq -r '.ETag' raw.json)

          # DistributionConfig만 추출
          jq '.DistributionConfig' raw.json > config-only.json

          # OriginPath 수정
          jq --arg SLOT "$SLOT" \
            '.Origins.Items[0].OriginPath = "/frontend/prod/\($SLOT)"' \
            config-only.json > updated-config.json

          # 업데이트 적용
          aws cloudfront update-distribution \
            --id $DIST_ID \
            --if-match $ETAG \
            --distribution-config file://updated-config.json

      - name: Invalidate CloudFront cache
        run: |
          SLOT="${{ needs.deploy.outputs.fe_slot }}"
          aws cloudfront create-invalidation \
            --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
            --paths "/" "/index.html" "/assets/*.js" "/assets/*.css"
