apiVersion: apps/v1
kind: Deployment
metadata:
  name: onthetop-backend-app
  labels:
    app: onthetop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onthetop-backend
  template:
    metadata:
      labels:
        app: onthetop-backend
    spec:
      containers:
      - name: onthetop-backend-container
        image: luckyprice1103/onthetop-backend:v2.0.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http-app
        resources:
          limits: # 컨테이너가 사용할 수 있는 최대 자원 제한
            memory: "512Mi" # 512MB 메모리 제한 (기존 512m에서 변경)
            cpu: "0.5"    # 0.5 vCPU 제한 (기존 0.5에서 변경)
        env:
        # 1. OTLP 엔드포인트 주소 변경
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://my-signoz-otel-collector.signoz.svc.cluster.local:4317"

        # 2. OTLP 프로토콜 설정 (gRPC)
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"

        # 3. 서비스 이름과 환경을 명확히 구분 (가장 중요!)
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=onthetop-backend-prod,deployment.environment=prod"

        # 4. 메트릭스는 여전히 사용 안 함
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: SPRING_PROFILES_ACTIVE # Spring 프로파일 설정
          value: "prod"
        - name: PORT # 애플리케이션 포트 (ConfigMap에서 가져옴)
          valueFrom:
            configMapKeyRef:
              name: onthetop-backend-config
              key: PORT
        - name: BE_VERSION # Docker 이미지 태그에 사용될 변수 (ConfigMap에서 가져옴)
          valueFrom:
            configMapKeyRef:
              name: onthetop-backend-config
              key: BE_VERSION


        volumeMounts:
        - name: secrets-properties-volume # 아래 volumes 섹션에서 정의한 볼륨 이름
          mountPath: "/app/secrets.properties" # 컨테이너 내부에서 파일이 마운트될 경로
          subPath: "secrets.properties" # Secret 내의 'secrets.properties' 키를 파일 이름으로 사용
          readOnly: true # 읽기 전용으로 마운트
        - name: logs-volume # 로그 볼륨 (임시 저장소)
          mountPath: "/logs" # 컨테이너 내부 로그 경로

        # 애플리케이션 시작 인자 (docker run 명령의 마지막 부분과 유사)
        args:
        - "--logging.file.name=/logs/backend.log"
        - "--spring.config.additional-location=file:/app/secrets.properties"

      volumes:
      - name: secrets-properties-volume # Secret을 볼륨으로 정의
        secret:
          secretName: onthetop-backend-secrets # ExternalSecret에 의해 생성될 Kubernetes Secret의 이름
      - name: logs-volume # 임시 로그 볼륨 정의 (Pod 종료 시 내용 사라짐)
        emptyDir: {}
